//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoDauBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuiEmail
    {
        public int id { get; set; }
        public int Tag { get; set; }
        public int Loai { get; set; }
        public System.DateTime Ngay { get; set; }
        public string MaGV { get; set; }
        public string Email { get; set; }
        public string FromTo { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
    }
}
