//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoDauBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int id { get; set; }
        public System.DateTime on { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public Nullable<System.DateTime> at { get; set; }
    }
}
