//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoDauBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoGhiChu
    {
        public int id { get; set; }
        public int idTKB { get; set; }
        public System.DateTime NgayGhi { get; set; }
        public System.DateTime NgaySua { get; set; }
        public System.TimeSpan GioBD { get; set; }
        public Nullable<System.TimeSpan> GioKT { get; set; }
        public byte DanhGia { get; set; }
        public string NoiDung { get; set; }
        public string Email { get; set; }
    
        public virtual ThoiKhoaBieu ThoiKhoaBieu { get; set; }
    }
}
