//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoDauBai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThoiKhoaBieu
    {
        public int id { get; set; }
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public byte SoTinChi { get; set; }
        public string NhomTo { get; set; }
        public string ToTH { get; set; }
        public string TenToHop { get; set; }
        public string MaNganh { get; set; }
        public string MaLop { get; set; }
        public string TenLop { get; set; }
        public short TongSoSV { get; set; }
        public byte ThuKieuSo { get; set; }
        public byte TietBD { get; set; }
        public byte SoTiet { get; set; }
        public string MaGV { get; set; }
        public string MaPH { get; set; }
    }
}
